openapi: "3.0.0"
info:
  title: Mock API
  version: 1.0.0
  description: Mock API to show how app work
  termsOfService: http://swagger.io/terms/
  contact:
    name: Ganesha
    email: reekoheek@gmail.com
    url: http://sagara.id
info:
  version: 1.0.0
  title: Swagger Petstore
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
servers:
  - url: http://localhost:3000/api
  - url: https://other.domain/api
paths:
  /now:
    get:
      summary: Get current time
      description: Get current time of server
      responses:
        200:
          description: Object of time
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Time"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Time:
      properties:
        date:
          type: string
          description: ISO 8601 format date
    Error:
      properties:
        code:
          type: string
        message:
          type: string
        fields:
          type: string
